image: "python:3.8"

stages:
  - Lint
  - Test

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip wheel

flake8:
  stage: Lint
  allow_failure: false
  script:
    - python -m pip install flake8
    - flake8 template_repo
    - flake8 tests

pytest:
  stage: Test
  script:
    - python -m pip install pytest
    # install dependencies
    - pip install -e .[all]
    # show installed packages
    - pip freeze
    - pytest -v tests
